language: cpp
dist: trusty

matrix:
    include:
     
    - os: linux
        script:      
            - echo `ls`
            - echo `which cmake` 

    - os: 
        osx_image: xcode7.3
        script:      
            - echo `ls`
            - echo `which cmake` 




